---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-python--service
  # namespace: default
spec:
  selector:
    app: helloworld-python
  ports:
  - name: http
    protocol: "TCP"
    port: 80
    targetPort: 8080
  # type: LoadBalancer
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-python
  # namespace: default
spec:
  selector:
    matchLabels:
      app: helloworld-python
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-python
    spec:
      containers:
      - name: helloworld-python
        image: docker.io/emayssatware/helloworld-python:latest
        # imagePullPolicy: Never
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: TARGET
          value: "Python Sample v1"
